In [7]:
my_course = [1,2,3]

In [8]:
import numpy as np

In [9]:
np.array(my_course)

array([1, 2, 3])

In [15]:
my_math=[[1,2,3],[4,5,6],[7,8,9]]

In [16]:
np.array(my_math)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
np.arange(0,11,1)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [20]:
np.zeros(4)

array([0., 0., 0., 0.])

In [22]:
np.zeros((6,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [23]:
np.ones(1)

array([1.])

In [28]:
np.ones(3)

array([1., 1., 1.])

In [30]:
np.linspace(0,6,20)

array([0.        , 0.31578947, 0.63157895, 0.94736842, 1.26315789,
       1.57894737, 1.89473684, 2.21052632, 2.52631579, 2.84210526,
       3.15789474, 3.47368421, 3.78947368, 4.10526316, 4.42105263,
       4.73684211, 5.05263158, 5.36842105, 5.68421053, 6.        ])

In [31]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [32]:
np.random.rand(3)

array([0.44924248, 0.23866381, 0.04634007])

In [34]:
np.random.rand(6,6)

array([[0.33196492, 0.45718787, 0.08590756, 0.19284746, 0.33265163,
        0.22715482],
       [0.56874801, 0.98453314, 0.3855169 , 0.26067265, 0.91921883,
        0.46655741],
       [0.20816851, 0.61567334, 0.96492701, 0.31927339, 0.91073592,
        0.48200313],
       [0.21461978, 0.068235  , 0.77787822, 0.85208758, 0.58594573,
        0.23026644],
       [0.59967934, 0.40605817, 0.34011477, 0.90182388, 0.898765  ,
        0.71474302],
       [0.67327658, 0.44637356, 0.80403175, 0.29267309, 0.26454533,
        0.55436474]])

In [37]:
np.random.randn(5)

array([-1.7983165 , -0.66710858,  1.2809445 , -0.49214396,  1.27842035])

In [38]:
np.random.randn(4,4)

array([[-0.49220604, -0.25964887,  0.48841931,  1.25344412],
       [-0.92229284,  0.34503074,  0.13352555,  0.40972247],
       [-0.12255083,  1.05087038,  0.98081196, -2.78785573],
       [-1.03559899, -0.37972647,  0.33184661,  0.4188787 ]])

In [40]:
np.random.randint(5)

3

In [46]:
np.random.randint(3,10,10)

array([6, 7, 5, 5, 5, 8, 5, 4, 5, 9])

In [50]:
arr = np.arange(25)

In [51]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [55]:
rar = np.random.randint(0,50,10)

In [57]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [58]:
rar

array([30, 44,  3, 16, 34, 22,  0, 44, 48,  2])

In [59]:
rar.max()

48

In [60]:
rar.min()

0

In [61]:
rar.argmin()

6

In [62]:
rar.argmax()

8

In [63]:
rar = (5,5)

In [65]:
rar

(5, 5)

In [68]:
arr.shape

(25,)

In [86]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [89]:
arr.reshape(1,25).shape

(1, 25)

In [90]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [91]:
arr.dtype

dtype('int32')

In [6]:
import numpy as np

In [7]:
rar = np.arange(0,21)

In [8]:
rar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [9]:
rar[6]

6

In [10]:
rar[2:7]

array([2, 3, 4, 5, 6])

In [11]:
rar[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
rar[11:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [13]:
rar[0:15] = 50

In [14]:
rar

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 15, 16,
       17, 18, 19, 20])

In [15]:
rar = np.arange(0,11)

In [16]:
rar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
slice_of_rar = rar[:6]

In [18]:
slice_of_rar

array([0, 1, 2, 3, 4, 5])

In [19]:
rar_copy = rar.copy()

In [20]:
rar_copy

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [21]:
rar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [22]:
rar_copy[:] = 50

In [23]:
rar_copy

array([50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50])

In [24]:
slice_of_rar[:] = 1

In [25]:
slice_of_rar

array([1, 1, 1, 1, 1, 1])

In [26]:
rar

array([ 1,  1,  1,  1,  1,  1,  6,  7,  8,  9, 10])

In [27]:
rar_copy = rar.copy()

In [28]:
rar_copy

array([ 1,  1,  1,  1,  1,  1,  6,  7,  8,  9, 10])

In [29]:
rar_copy[:] = 40

In [30]:
rar_copy

array([40, 40, 40, 40, 40, 40, 40, 40, 40, 40, 40])

In [31]:
rar_2d = np.array([[3,5,7],[1,19,10],[34,56,40]])

In [32]:
rar_2d

array([[ 3,  5,  7],
       [ 1, 19, 10],
       [34, 56, 40]])

In [33]:
rar_2d[0,2]

7

In [34]:
rar_2d[:2,2:]

array([[ 7],
       [10]])

In [35]:
rar = np.arange(0,21)

In [36]:
rar

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [37]:
rar > 6

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [38]:
bool_rar = rar > 6

In [39]:
bool_rar

array([False, False, False, False, False, False, False,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True])

In [40]:
rar[bool_rar]

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [41]:
rar[rar<2]

array([0, 1])

In [42]:
rar = np.arange(20).reshape(2,10)

In [43]:
rar

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [44]:
rar[0:2,4:6]

array([[ 4,  5],
       [14, 15]])

In [45]:
import numpy as np

In [48]:
rar = np.arange(1,11)
rar

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [51]:
rar + rar 

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [52]:
rar - rar 

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [53]:
rar * 5

array([ 5, 10, 15, 20, 25, 30, 35, 40, 45, 50])

In [54]:
2 / rar 

array([2.        , 1.        , 0.66666667, 0.5       , 0.4       ,
       0.33333333, 0.28571429, 0.25      , 0.22222222, 0.2       ])

In [55]:
rar / rar 

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [56]:
rar ** 5

array([     1,     32,    243,   1024,   3125,   7776,  16807,  32768,
        59049, 100000], dtype=int32)

In [57]:
np.sqrt(rar)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [58]:
rar.max()

10

In [61]:
rar.min()

1

In [63]:
np.sin(rar)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [64]:
np.cos(rar)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362,  0.28366219,
        0.96017029,  0.75390225, -0.14550003, -0.91113026, -0.83907153])

In [65]:
np.cosh(rar)

array([1.54308063e+00, 3.76219569e+00, 1.00676620e+01, 2.73082328e+01,
       7.42099485e+01, 2.01715636e+02, 5.48317035e+02, 1.49047916e+03,
       4.05154203e+03, 1.10132329e+04])

In [66]:
np.exp(rar)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [67]:
np.arccosh(rar)

array([0.        , 1.3169579 , 1.76274717, 2.06343707, 2.29243167,
       2.47788873, 2.63391579, 2.76865938, 2.88727095, 2.99322285])